---


- name: Ensure group gubiq exists
  ansible.builtin.group:
    name: gubiq
    state: present

- name: create user account
  ansible.builtin.user:
    name: gubiq
    groups: gubiq
    shell: /bin/bash
    create_home: yes

- name: set perms on datadir
  file:
    state: directory
    path: "{{ datadir }}"
    owner: gubiq
    group: gubiq
    mode: '0755'

- name: create gubiq config dir
  file:
    dest: /usr/local/etc/gubiq/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: insert gubiq config
  template:
    src: gubiq.conf.toml.j2
    dest: /usr/local/etc/gubiq/gubiq.conf.toml
    mode: '0755'
    owner: gubiq
    group: gubiq

- name: download gubiq
  get_url:
    url: https://github.com/ubiq/go-ubiq/releases/download/v5.4.0/gubiq-linux-amd64
    dest: /tmp/gubiq-linux-amd64
    checksum: sha256:a813c1cbd523868dd4476ad0605fcbc816dfa0f205f9435548455e3fb81f15a3
    mode: '0755'

- name: copy gubiq to bindir
  ansible.builtin.copy:
    src: /tmp/gubiq-linux-amd64
    dest: /usr/local/bin/gubiq
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: create ufw firewall exception for gubiq websockets
  community.general.ufw:
    rule: allow
    port: 8546
    proto: tcp

- name: Install gubiq system service
  ansible.builtin.template:
    src: templates/gubiq.service.j2
    dest: /etc/systemd/system/gubiq.service
    owner: root
    group: root
    mode: '0755'
  notify: 
    - restart gubiq

- name: enable gubiq
  ansible.builtin.systemd:
      name: gubiq
      state: started
      enabled: yes